---
title: "Comments"
author: "Vanessa di Lego"
date: '2022-08-23'
output: pdf_document
---

## Impressão geral:

Excelente pergunta de pesquisa e trabalho muito relevante para o contexto brasileiro. Sugiro apenas que a literatura que vem da demografia e busca associar o conceito mais biológico com o populacional de envelhecimento seja mais explorado. Envio uma lista abaixo. Mas queria mencionar também um pouco da literatura que entra na "conversa" com alguns outros debates. Entender o que causa e caracteriza o envelhecimento é complexo e uma área enorme de pesquisa sujeito a muitos debates. Um grupo considera o envelhecimento algo programado (também chamado de teorias do envelhecimento programado Lee 2003, Hayflick 1977; 1985), e portanto entende o envelhecimento como “natural”, causado por mecanismos internos ao nosso próprio organismo. Por exemplo, a redução da secreção de hormônios sexuais, particularmente estrogênio nas mulheres, após a menopausa, cria condições para o desenvolvimento da osteoporose. Dessa forma, para a concepção de envelhecimento programado, o envelhecimento é decorrente de mecanismos de controle intrínsecos ao organismo que levam à deterioração, do mesmo modo como os genes programam outros estágios da vida, como diferenciação celular durante o desenvolvimento embrionário ou maturação sexual na adolescência.  Assim, trata-se de um processo típico e esperado do organismo, portanto um aspecto mais inerente à vida. O que fazemos portanto ao tratar de certos aspectos do envelhecimento é meramente adiar um processo que é natural. Ou seja, mesmo se eliminadas as doenças conhecidas relacionadas à idade avançada e as suas subsequentes causas de morte, ainda assim haveria mortalidade por senescência, ou seja, pela programação genética do organismo (velhice). Essa linha de raciocínio é o que é colocado em debate também para avaliar a compressäo-expansäo de morbidade. Se é verdade que o envelhecimento é um processo natural, intrínseco e que o que fazemos é meramente adiar um processo, entäo "avancos" seriam caracterizados por um adiamento desse processo e das suas causas associadas. O que desafia isso um pouco é o caso dos centenários/super centenários. Por serem muito heterogênos em termos de aspectos mensuráveis - tais como status socioeconômico, estilo de vida, etc, parece que há algo que escapa essas mensuracoes. 

Outros estudiosos entendem o envelhecimento como um acúmulo de danos estruturais (como danos ou erros mitocondriais), e desgaste - chamado de “wear and tear” (Holliday 2004; Baynes 2000, de Grey 2000). Logo, para esses estudiosos, o envelhecimento não é o resultado de um programa específico do organismo, mas sim uma resultante de um somatório de efeitos de diversos tipos de impactos ambientais e genéticos, tais como danos devido a radiação, toxinas químicas, metais pesados e radicais livres. Trata-se da diminuição da capacidade de reparação celular em decorrência de danos na própria estrutura do DNA. Dessa forma, ao tratar o envelhecimento como um processo de acúmulo de danos, é o mesmo que tratá-lo como uma alteração metabólica similar a de uma doença. Nessa perspectiva, o envelhecimento pode ser entendido como uma doenca e o desenvolvimento da área médica e tecnológica seriam ajustadas a essa visäo, com a intencao de reverter o processo em uma reengenharia celular.  Isso é bem controverso e como discutimos na arguicao, bem problemático.

O que eu sugiro é talvez fazer uma leitura mais revisionista/crítica da demografia que trata disso, para conectar com as suas idéias. Segue uma lista no final desse documento que eu acredito ser bem útil. De modo geral, acho que o arcabouço de compressão/expansão de morbidade também vai te ajudar bastante a situar o debate, já que há uma interacao íntima entre ganhos em expectativa de vida e saúde que precisa ser debatida para entender as consequencias do envelhecimento populacional do ponto de vista que você coloca, como política pública.


## Pergunta Central:

*Qual o significado, o potencial e os limites da abordagem prospectiva na determinação da agenda de envelhecimento populacional no Brasil do Século XXI?*

A pergunta é bem clara, mas também bem ampla. Importante pensar como será oferecida uma resposta a cada um desses itens. Como o foco é na determinação da agenda, vai ser essencial fazer uma discussão sobre o impacto desse indicador. Uma coisa são as limitaçoes de um indicador do ponto de vista puramente teórico, ou metodológico. Outra coisa são as limitaçoes de um indicador do ponto de vista da sua aplicação para política pública/agenda. São passos importantes na sua tese, e apesar de interconectados, distintos.

## Pressuposto importante em relação ao indicador prospectivo:

*Quanto maior for a desigualdade sustentada no tempo, menor será a capacidade de mensurar o envelhecimento populacional com a abordagem prospectiva. Em síntese, há uma relação inversamente proporcional entre a assertividade da abordagem prospectiva e a condição de desigualdade no processo de envelhecimento populacional*.

Essa sua frase é bem forte e dá a entender que há uma simetria entre o indicador prospectivo e a proporção de pessoas idosas na população. É isso mesmo que você quer dizer? É isso que o indicador afirma? Como falamos na arguição oral, há sempre um tom nas entrelinhas quando você fala que há uma inerente limitação do indicador em contextos desiguais. Acho importante deixar isso bem claro, porque é um pressuposto importante que você faz e que acaba guiando todo o resto da discussão. Nas suas hipótese, também é colocado que: "A abordagem prospectiva é insuficiente para mensurar o envelhecimento e determinar a agenda pública de envelhecimento em contextos de sociedades que têm a ampliação da longevidade combinada com a manutenção de condições de desigualdade." Qual é o seu instinto/pensamento que levou a achar que a bordagem prospectiva é limitadora no contexto de países em desenvolvimento?

*Na medida em que os indivíduos da população envelhecem, surge a senescência e o aumento da probabilidade de morte, bem como o aumento das taxas de mortalidade específicas por idade.*

Na verdade, a senescência não surge. Isso até mesmo contradiz a forma como você elabora o argumento do envelhecimento biológico enquanto um processo. Há também um questão aqui de associar o aumento das taxas de mortalidade com a idade e algumas distorcoes que acontecem ao longo do ciclo de vida, como o aumento em idades mais jovens adultas e em idades bem avancadas, onde tem-se mostrado que atinge-se um plateau de extrema idade. Ou seja, o risco de morte se mantém estável -- apesar de alto. Isso significa que a funcao de mortalidade só tem uma constancia mesmo em idades adultas, ou mais particularmente entre 30 e 80 anos- o que condiz com a chamada "lei" de Gompertz.

*A utilização de curvas de sobrevivência é útil para fazer inferências acerca de alterações na longevidade de uma população, mas não informa sobre qualquer alteração na composição etária de uma população porque não considera as alterações na fecundidade e migração* 

Essa frase na página 22 não é muito precisa. Na verdade, há formas em demografia em que é possível estabelecer uma relação direta entre a curva de sobrevivência, composição etária e nascimentos. Por exemplo, em populacao estável, você pode estabelecer que:

$$c(a,t)= be^{-ra}l(a)$$ 

onde $c(a,t)$ é a composição etária da população, $b$ säo os nascimentos e $l(a)$ é a funcao de sobrevivência. Isso vem da relação estabelecida por Lotka: $1=\int_{\alpha}^{\beta}e^{-ra}l(a)m(a)da$ e alguns outros desenvolvimentos em demografia formal sobre taxas de crescimento populacional. Ponto é que essa afirmação, por ser imprecisa, pode gerar/levantar críticas desnecessárias por parte de demógrafos mais formais.

Eu entendo que a idade cronológica do ano índice foi escolhida com base na definição de idoso no Brasil (60 anos). No entanto, seria importante fazer uma análise de robustez, onde diferentes idades são usadas para avaliar como a escolha do padrão interfere nos resultados. Como há toda uma discussão no início do trabalho sobre diferenças entre países em desenvolvimento e desenvolvidos, é importante usar o critério de 65 também e aumentar paulatinamente até cerca de 70/75. Será que o método se comporta da mesma forma? Não há nada intrínseco ao método que sugira diferenças. É importante demonstrar/explorar isso.

## A escolha técnica para interpolar expectativa de vida

A interpolação da expectativa de sobrevida no ano índice segundo a idade cronológica escolhida e as expectativas de sobrevida disponíveis no ano índice são feitas usando uma função linear. Mas essa não é a forma mais acurada de interpolar expectativa de vida, devido ao padrão subjacente de mortalidade. O ideal é interpolar as taxas específica de mortalidade e então possivelmente ajustar idades mais avançadas usando métodos como "Kannisto", "Kannisto_Makeham", "Makeham", "Gompertz", "Gama-Gompertz", "Beard", "Beard_Makeham", "Quadratic", etc. Apesar da trajetória da $e_x$ ser linear, a função subjacente não é. Há um conjunto de rotinas no pacote [**DemoTools**](https://timriffe.github.io/DemoTools/) elaborado pelo Tim Riffe em que você pode transformar uma tabela de vida em cinco anos para uma tabela de vida simples. Outra coisa importante é que na tabela de vida que você usa como ponto de partida fecha a tabela de vida em uma idade diferente do ano índice. Isso pode gerar distorçoes....Quando a idade limite usada para truncar a tabela, ou, em outras palavras, a censura à direita da tabela de vida é diferente comparativamente no final haverá diferenças. Como o interesse é em expectativa de vida remanescente, ou seja, condicionada a certa idade, isso pode ser ainda mais importante. Sugiro usar o mesmo conjunto de rotinas para extrapolar a última idade e assim ter as tabelas harmonizadas com a mesma idade limite.

## Referências sugeridas:

Crimmins E, Kim JK, Vasunilashorn S. Biodemography: new approaches to understanding trends and differences in population health and mortality. Demography. 2010;47 Suppl(Suppl 1):S41-64. doi: 10.1353/dem.2010.0005. PMID: 21302421; PMCID: PMC5870619.

OEPPEN, J., and J. W. VAUPEL. 2002. “Broken Limits to Life Expectancy”. Science 296 (5570): 1029–1031.

OLSHANSKY SJ, CARNES BA, CASSEL C, et al. (1990). In search of  Methuselah: estimating the upper limits to human longevity. Science;250:634–640.

OLSHANSKY, S.J. et al. (2001). Prospects for human longevity. Science 291, 1491–1492.

VAUPEL, J. W. (1998). “Demographic Analysis of Aging and Longevity”. American Economic Review 88 (2): 242–247.

HAYFLICK, L. (2000). The future of ageing. Nature 408, 267–269. 

KASS, L. (2001). L’Chaim and its limits: why not immortality? First Things 113, 17–24. LIN, K. Modern Biological Theories of Aging- commentary- Volume 1, Number 2; 72-74, October 2010. Aging and Disease. 

LIVI-BACCI, M. (1991). Population and Nutrition: An Essay on European Demographic History. Cambridge: Cambridge University Press.

MAGALHÃES, J. P. (2014). The Scientific Quest for Lasting Youth: Prospects for Curing Aging. REJUVENATION RESEARCH. Volume 17, Number 5. 

MANTON, K. G. (1982). Changing concepts of morbidity and mortality in the elderly population. Milbank Memorial Fund Quarterly/Health and Society, 60, 183–244. 

MCKEOWN, Thomas. (1976). The Modern Rise of Population. New York: Academic Press. MEHLMAN, M. (2011). Ethical and Legal Issues in Enhancement Research in Human Subjects, 20 Cambridge Quarterly of Healthcare Ethics 30-45 with Jessica Berg, Eric Juengst, and Eric Kodish.

SEEAR e PETTERSEN. (2009). In Search of Immortality: The Political Economy of Anti-aging Medicine. Medicine Studies 1:267–279.

FRIES, J. F. (1980). Aging, natural death, and the compression of morbidity. N Engl J Med. ;303:130–135. 
